apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
  - name: redis
    image: redis
    resources:
      requests:
        #cpu: 100m    # 没有配置，等于limits
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 300m
        #memory: 128Mi    # 没有配置
